<?php /* Copyright (C) Sourcemap 2011 */ ?>

<div id="document-content" class="container">
    <h1 id="document-title">Sourcemap Pro Account Pricing And Terms Of Service</h1>

<p style="text-align: left;" align="center">Sourcemap, Inc. (.Sourcemap.) allows Users (as defined by the Sourcemap Terms of Service) to enjoy additional features through a premium subscription service known as a Sourcemap Pro Account (.Pro Account.) for a fee. These Terms of Service (.Agreement.) constitute an agreement that describes the legal relationship between a User of the Pro Account and Sourcemap. User.s transactions and any other use of the Pro Account are subject to the terms in this Agreement.</p>
<h2 style="text-align: left;">1.         Acceptance.</h2>
<p style="text-align: left;">As a condition of use of the Pro Account, User hereby accepts and agrees to (1) the Agreement; and (2) all other terms and conditions that apply to use of the Sourcemap website, including without limitation Sourcemap's then applicable Terms of Service, Privacy Policy, and Digital Millennium Copyright Act Notice Policy, as from time to time posted on Sourcemap.s website.</p>
<h2 style="text-align: left;">2.         Payment and Refund Policy.</h2>
<h3 style="text-align: left;"> (a)        Price and Subscription.</h3>
<p style="text-align: left;">User agrees to pay an annual Subscription Fee of ninety-nine dollars ($99) in exchange for the use of the Pro Account. Subject to Paragraph 8 below (Modifications to Agreement and Pro Account), Sourcemap reserves the right to change the Subscription Fee at any time for any or no reason with or without notice. The subscription to the Pro Account will annually renew until User or Sourcemap terminates User.s subscription.</p>
<h3 style="text-align: left;">(b)        Payment.</h3>
<p style="text-align: left;">Sourcemap accepts payment by credit card and any other form of payment that Sourcemap makes available to User. User agrees to (i) pay for the Pro Account and that (ii) abide by any relevant Terms of Service or other legal agreement (including without limitation the Sourcemap Terms of Use), whether with Sourcemap or a third party that governs User.s use of a given payment processing method. User agrees that Sourcemap may charge User.s credit card or other form of payment that User indicates for use of the Pro Account, along with any additional amounts (including any taxes). Sourcemap reserves the right to add or remove payment processing methods at its sole discretion with or without notice to User.</p>
<h3 style="text-align: left;">(c)        Termination.</h3>
<p style="text-align: left;">User reserves the right to terminate User.s subscription for any or no reason at any time. Sourcemap will not provide User with a refund, on a <em>pro rata</em> basis or otherwise. Sourcemap reserves the right to terminate User.s Sourcemap account(s), to restrict access to a User.s Sourcemap account(s) or to the Site in whole or in part, or to delete any content posted through a User.s Sourcemap account(s), with or without notice, for any or no reason, and without any liability. User acknowledges that Sourcemap reserves the right to modify, suspend, or discontinue the Site or access to the Site with or without any notice at any time and without any liability to any User.</p>
<h3 style="text-align: left;">3.         Restrictions.</h3>
<p style="text-align: left;">User shall not attempt or engage in acts that are or are perceived to be directed against the interests of the Pro Account or any third-party, including, without limitation, the following: (a) using the Pro Account in contravention of any other agreement to which the User is a party, including without limitation any employment agreement to which the User may be a party; (b) emulating or faking usage of the Pro Account; (c) copying, selling, renting or sublicensing all or any part of the Pro Account content to any third-party; (d) using the Pro Account in an illegal manner or for an illegal purpose; (e) circumventing, reverse-engineering, modifying, disabling, or otherwise tampering with any security technology used to protect the Pro Account; accessing the Pro Account other than by means authorized by Sourcemap; or (f) removing or modifying any proprietary or other notices or labels on the Pro Account. Further, User may not encourage or help anyone else to do any of the foregoing things.</p>
<h3 style="text-align: left;">4.         Other User Accounts and Information.</h3>
<p style="text-align: left;">Sourcemap is not obligated to comply with User.s requests to terminate any account or remove any information contributed by another User.</p>
<h3 style="text-align: left;">5.         Disclaimers.</h3>
<p style="text-align: left;">(a)        THE SOURCEMAP PRO ACCOUNT AND ALL AFFILIATED SERVICES ARE PROVIDED ON AN .AS IS. AND .AS AVAILABLE. BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR OTHERWISE.   WITHOUT LIMITATION, SOURCEMAP DISCLAIMS ANY AND ALL WARRANTIES REGARDING THE SECURITY, RELIABILITY, TIMELINESS, AND PERFORMANCE OF ALL SERVICES ASSOCIATED WITH USE OF THE SITE.   SOURCEMAP MAKES NO WARRANTY, EXPRESS OR IMPLIED, THAT A USER.S USE OF THE PRO ACCOUNT WILL BE UNINTERRUPTED, TIMELY, OR ERROR-FREE.   SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF CERTAIN WARRANTIES, SO PORTIONS OF THE ABOVE DISCLAIMER MAY NOT APPLY TO SOME USERS.</p>
<p style="text-align: left;">(b)        CONSISTENT WITH THE ABOVE, SOURCEMAP DISCLAIMS ALL RESPONSIBILITY AND LIABILITY FOR THE AVAILABILITY, TIMELINESS, SECURITY OR RELIABILITY OF THE PRO ACCOUNT.</p>
<h3 style="text-align: left;">6.         Limitation on Liabilities and Waiver of Certain Damages.</h3>
<p style="text-align: left;">(a)        TO THE EXTENT NOT PROHIBITED BY APPLICABLE LAW, SOURCEMAP WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF OR INABILITY TO USE THE PRO ACCOUNT. USERS EXPRESSLY AGREE THAT THEIR USE OF THE PRO ACCOUNT IS SOLEY AT THEIR OWN RISK. UNDER NO CIRCUMSTANCES SHALL SOURCEMAP BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, INCOME, OR BUSINESS OPPORTUNITIES, REGARDLESS OF THE NATURE OF THE CLAIM OR THE FORM OF ACTION, ARISING OUT OF OR CONNECTED WITH THIS AGREEMENT OR THE PRO ACCOUNT, EVEN IF SOURCEMASP HAS BEEN NOTIFIED OF THE POSSIBILITY OF ANY DAMAGES.</p>
<p style="text-align: left;">(b)        IN NO EVENT WILL SOURCEMAP.S AGGREGATE LIABILITY FOR ANY AND ALL CAUSES OF ACTION BROUGHT BY USER OR USER.S AGENTS ARISING FROM OR RELATED TO THIS AGREEMENT, SOURCEMAP, OR PRO ACCOUNT EXCEED THE GREATER OF $99 OR THE AMOUNT USER HAS PAID SOURCEMAP IN THE PAST 12 MONTHS THAT WERE ACUTALLY RECEIVED AND RETAINED BY SOURCEMAP FROM USER FOR THE SERVICES.</p>
<h2 style="text-align: left;">7.         Indemnification.</h2>
<p style="text-align: left;">Each User agrees, at User.s own expense, to indemnify, defend, save, and hold harmless Sourcemap, its creators, employees, affiliates, officers, directors, contributors, and/or other representatives from and against any and all judgments, losses, damages, liabilities, costs, or expenses (including but not limited to reasonable attorneys. fees and legal expenses) associated with or arising from (a) the User.s use of the Pro Account; (b) the User.s submissions to the Pro Account; (c) any breach or claimed breach by such User of any representations, warranties, and/or agreements set forth in this Agreement and other Sourcemap agreements, including without limitation Sourcemap's then applicable Terms of Service, Privacy Policy, and Digital Millennium Copyright Act Notice Policy; (d) any tortuous or grossly negligent act or omission by the User, its agents, and/or independent contractors, including but not limited to consequential damages, loss of profits, loss of business opportunities, and loss of income.</p>
<h2 style="text-align: left;">8.         Modifications to Agreement and Pro Account.</h2>
<p style="text-align: left;">Sourcemap reserves the right to change the availability of the Pro Account and/or pricing with or without notice. In addition, Sourcemap reserves the right to modify, suspend, or discontinue the Pro Account or access to the Pro Account with or without notice to User without any liability to User or any third party for any such modifications, suspension, or termination. Sourcemap may also, in its sole and absolute discretion, change these Terms of Service from time to time with or without notice. User is responsible for periodically reviewing the most up-to-date version of these Terms of Service to ensure User is familiar with the Terms of Service. Such modification shall be effective upon its posting to the Site. User.s continued use of the Pro Account constitutes User.s agreement to abide by the Terms of Service as changed. If User objects to any such changes, User.s sole recourse will be to terminate User.s subscription and stop using the Pro Account.</p>
<h2 style="text-align: left;">9.         Severability.</h2>
<p style="text-align: left;">If any provision of the Terms of the Service shall be deemed unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these terms and conditions and shall not affect the validity and enforceability of any remaining provisions. Applicable law may not allow the limitation or exclusion of liability or incidental or consequential damages, so the above limitation or exclusion may not apply to User. In such cases, Sourcemap.s liability will be limited to the fullest extent permitted by applicable law.</p>
<h2 style="text-align: left;">10.       No Waiver of Terms.</h2>
<p style="text-align: left;">Failure of Sourcemap to exercise or enforce any right or provision of these Terms shall not be deemed a waiver of such right or provision in that or any other instance.</p>
<h2 style="text-align: left;">11.       Jurisdiction and Governing Law.</h2>
<p style="text-align: left;">These terms and conditions are governed by the laws of the Commonwealth of Massachusetts, without regard to the rules of conflict of law that may cause the laws of another jurisdiction to apply. Users agree to the sole and exclusive jurisdiction and venue of the federal or state courts sitting in Suffolk County in the Commonwealth of Massachusetts in the event of a dispute of any kind arising from or relating to the Pro Account or user.s use or review of it.</p>

</div>
<div class="push"></div>
