#!/bin/bash

# db
export SMAP_DB="smap"
export SMAP_DBUSER="smap"
export SMAP_DBPASS="smap"
export SMAP_DBHOST="localhost"

export SMAPDIR="/home/reed/devel/mit/sourcemap/smap/trunk/"

# for phing
export PHP_CLASSPATH="${SMAPDIR}www/application/classes/"
export PHING_HOME="${SMAPDIR}tools/"
