#!/bin/bash

# env
export SOURCEMAP_ENV="development"

# db
export SMAP_DB="sourcemap"
export SMAP_DBUSER="sourcemap"
export SMAP_DBPASS="sourcemap"
export SMAP_DBHOST="localhost"

export SOURCEMAP_DIR="/home/maalox/sourcemap/trunk/"

# for phing
export PHP_CLASSPATH="${SOURCEMAP_DIR}www/application/classes/"
export PHING_HOME="${SOURCEMAP_DIR}tools/"
