#!/bin/bash

if [ -n "${1}" ]; then
    if [ -f "env/${1}" ]; then
        SOURCEMAP_ENV="${1}"
        echo "activated ${SOURCEMAP_ENV}"
        source "env/${SOURCEMAP_ENV}"
    else
        echo "invalid env"
    fi
else
    echo "no env specified"
fi
