#!/bin/bash

# Copyright (C) Sourcemap 2011
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU Affero General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this
# program. If not, see <http://www.gnu.org/licenses/>.

if [ ! -n "${1}" ]; then
    echo -e "\t- ** FATAL: No outdir parameter given.\n"
    exit 1
fi

if [ ! -d "${1}" ]; then
    echo -e "\t- ** FATAL: Output directory doesn't exist.\n"
    exit 1
fi

outputdir="${1}"

databases=(`psql -lAt | cut -d'|' -f1 -`)

suffix=`date +%Y%m%d-%H%M%S`

for db in "${databases[@]}"; 
do
    dump=`echo -e "${db}" | grep "sourcemap" | awk '{print $1}'`
    if [ "${dump}" ]; then
        pg_dump "${dump}" | bzip2 > "${outputdir}/${db}-${suffix}.dump.sql.bz2"
    fi
done;
