#!/bin/bash

# Copyright (C) Sourcemap 2011
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU Affero General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this
# program. If not, see <http://www.gnu.org/licenses/>.

usage="2 arguments required: target directory and symbolic link to point at it."

if [ "$#" -ne 2 ]; then
    echo "$usage"
    exit 1
fi

source env/dev

newbuilddir=`date +sourcemap_deploy_%Y-%m-%d_%H%M%S_%N`
newrollbackdir=`date +sourcemap_rollback_%Y-%m-%d_%H%M%S_%N`

builddir="${SOURCEMAP_DIR}build"
targetdir="$1"
if [ ! -d "$1" ]; then
    echo "invalid target"
    echo "$usage"
    exit 1
fi

linknm="$2"

rollbackdir="${targetdir}/${newrollbackdir}"

if [ -d "${rollbackdir}" ]; then
    echo "rollback dir ${rollbackdir} exists. bailing."
    exit 1
else
    if [ -h "${linknm}" ]; then
        #mkdir "${rollbackdir}"
        echo "copying current link target of ${linknm} to ${rollbackdir}"
        cp -RL "${linknm}" "${rollbackdir}"
    fi
fi

deploydir="${targetdir}/${newbuilddir}"

if [ -d "${deploydir}" ]; then
    echo "deploy dir ${deploydir} exists. bailing."
    exit 1
else
    mkdir "${deploydir}"
    echo "copying files from ${builddir} to ${deploydir}"
    cp --recursive "${builddir}"/* "${deploydir}"
fi

echo "Pointing link ${linknm} to ${deploydir}..."
if [ -h "${linknm}" ]; then
    rm "${linknm}"
fi
ln -s "${deploydir}" "${linknm}"
