#!/usr/bin/env php
<?php
# Copyright (C) Sourcemap 2011
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU Affero General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this
# program. If not, see <http://www.gnu.org/licenses/>.

// fetches and converts sourcemap data from
// original sourcemap web services and generates
// json suitable for posting to the new SM api
if(php_sapi_name() !== 'cli') die('cli only');

if($argc == 3)
    define('FETCH_URL', 'http://'.$argv[1].'/services/objects/'.$argv[2]);
else
    die("Supplychain url required as first parameter.\n");

// sourcemap-specific bootstrap
define('SOURCEMAP_DIR', getenv('SOURCEMAP_DIR') ? 
    rtrim(getenv('SOURCEMAP_DIR'), DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR : 
    realpath(dirname(dirname(__FILE__))).DIRECTORY_SEPARATOR
);
define('SUPPRESS_REQUEST', true);

require_once(SOURCEMAP_DIR.'/www/index.php');
function fetch_sc($url) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_URL, $url);
    $resp = curl_exec($ch);
    return $resp;
    //$scdata = @json_decode($resp);
    //return $scdata;
}

$oldsc = fetch_sc(FETCH_URL);

echo $oldsc;

