#!/bin/bash

# Copyright (C) Sourcemap 2011
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU Affero General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this
# program. If not, see <http://www.gnu.org/licenses/>.

LOCAL_DEV_CONFIG="local-dev-config.source"

if [ ! -f "$LOCAL_DEV_CONFIG" ]; then
    echo ""
    echo -e "\tNo local dev configuration."
    echo -e "\t---------------------------"
    echo -e "\tDid you copy tools/local-dev-config.source.example to tools/local-dev-config.source?"
    echo ""
    exit 1
fi

# source configuration
# set defaults otherwise.

. "$LOCAL_DEV_CONFIG"

if [ ! -n "${LOCAL_DEV_APPS}" ]; then
    echo "FATAL: LOCAL_DEV_APPS variable not set. $LOCAL_DEV_APPS"
    exit 1
fi

# make cache and log directories
for app in ${LOCAL_DEV_APPS[@]}
do
echo -e "\n\tMaking cache directory for app \"$app\" @ /var/cache/$LOCAL_DEV_TKNM/$app."
mkdir -p "/var/cache/$LOCAL_DEV_TKNM/$app"

echo -e "\tMaking log directory for app \"$app\" @ /var/log/$LOCAL_DEV_TKNM/$app."
mkdir -p "/var/log/$LOCAL_DEV_TKNM/$app"

# change owner to www-data (apache)
echo -e "\tSetting permissions on cache and log directories..."
chown -R www-data:`whoami`  "/var/cache/$LOCAL_DEV_TKNM/$app"
chown -R www-data:`whoami` "/var/log/$LOCAL_DEV_TKNM/$app"

chmod -R g+w "/var/cache/$LOCAL_DEV_TKNM/$app"
chmod -R g+w "/var/log/$LOCAL_DEV_TKNM/$app"

done

echo -e "\n\t...done!"
