#!/usr/local/bin/php -f
<?php

define("SOURCEMAP_BASEURL", "www.sourcemap.org/");
define("OUTDIR", "./migrate/".time()."/");

function fetch_oids($o=0, $l=100) {
    $ch = curl_init();
    $url = 'http://'.SOURCEMAP_BASEURL.'services/objects/';
    curl_setopt($ch, CURLOPT_URL, $url.'?o='.$o.'&l='.$l);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $data = curl_exec($ch);
    return @json_decode($data);
}

$o = 0; $l = 100; $c = 0;

echo "mkdir -p ".OUTDIR."\n";

while($oids = fetch_oids($o,$l)) {
    $o += $l;
    foreach($oids as $i => $oid) {
        $c++;
        $outfnm = $oid.".sm.migrate.json";
        echo "echo \"Migrating object $oid ($c)...\"\n";
        echo "./fetch-and-convert-sc \"".SOURCEMAP_BASEURL."\" $oid > ".OUTDIR."$outfnm\n";
        echo "echo \"...written to ".OUTDIR."$outfnm\"\n";
    }
}
