#!/usr/local/bin/php -f
<?php
# Copyright (C) Sourcemap 2011
# This program is free software: you can redistribute it and/or modify it under the terms
# of the GNU Affero General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this
# program. If not, see <http://www.gnu.org/licenses/>.

define("SOURCEMAP_BASEURL", "www.sourcemap.org/");
define("OUTDIR", "./migrate/".time()."/");
define("FETCHONLY", true);

function fetch_oids($o=0, $l=100) {
    $ch = curl_init();
    $url = 'http://'.SOURCEMAP_BASEURL.'services/objects/';
    curl_setopt($ch, CURLOPT_URL, $url.'?o='.$o.'&l='.$l);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $data = curl_exec($ch);
    return @json_decode($data);
}

$o = 0; $l = 100; $c = 0;

echo "mkdir -p ".OUTDIR."\n";

while($oids = fetch_oids($o,$l)) {
    $o += $l;
    foreach($oids as $i => $oid) {
        $c++;
        $outfnm = $oid.".sm.migrate.json";
        echo "echo \"Migrating object $oid ($c)...\"\n";
        if(defined("FETCHONLY") && FETCHONLY) {
            echo "./fetch-old-sc \"".SOURCEMAP_BASEURL."\" $oid > ".OUTDIR."$outfnm\n";
        } else {
            echo "./fetch-and-convert-sc \"".SOURCEMAP_BASEURL."\" $oid > ".OUTDIR."$outfnm\n";
        }
        echo "echo \"...written to ".OUTDIR."$outfnm\"\n";
    }
}
